### ISSUE TITLE
Can't find AMI image

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/OHDSI-in-a-Box#1]
I can't seem to find the AMI image. Is it region locked to a specific region? I am on the Ohio region. Thanks!

<img width="809" alt="iqvia-issue" src="https://user-images.githubusercontent.com/10423944/47304286-1ff9c800-d5f4-11e8-88b5-8be8d2156896.PNG">

**Comment by gaxhaje** [comment]
Also can't find the AMI image.

**Comment by ningyifan** [comment]
It works by searching in US East Region

**Comment by siannuzzi** [comment]
The issue has been resolved by ensuring that the US East Region is selected.
