### ISSUE TITLE
localhost:8080/atlas/#/home

### ISSUE THREAD

**Issue by scrtac** [OHDSI/OHDSI-in-a-Box#10]
HTTP Status 404 - Not Found
Hello
I need a hand with this, I'm trying to run atlas from the cloud but when the machine finally runs and is perfectly mounted, this inconvenience occurs when opening the browser from the remote desktop.
Any help?
![OHDSI](https://user-images.githubusercontent.com/55152360/64631378-9ba36580-d3bc-11e9-9c7b-b04454fbbadd.png)

**Comment by JamesSWiggins** [comment]
Hello.  I believe the problem is that your browser is pointed to http://localhost:8080/ and not http://localhost/.

Atlas is served from port 80 in this OHDSI-in-a-Box instance, not port 8080.  I hope this helps!!
