### ISSUE TITLE
How to connect my personal OMOP CDM database

### ISSUE THREAD

**Issue by irreversibly** [OHDSI/OHDSI-in-a-Box#11]

**Comment by JamesSWiggins** [comment]
You can connect to the local OMOP CDM database in the OHDSI-in-a-Box instance by using either the SQLWorkbench or pgAdmin4 tools in Linux or Windows, respectively.  It is also possible to connect the tools in this OHDSI-in-a-Box instance (Atlas, RStudio, SQLWorkbench/pgAdmin4, White Rabbit, etc.) to another OMOP CDM database hosted inside or outside of AWS.  To do that, you would edit the configuration of these tools to point to the network address for that database.
